version: '3'

volumes:
  pgdata:
      driver: local  

services:
  postgres:
      image: postgres:12
      volumes:
        - pgdata:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      ports:
        - 5432:5432

  keycloak:
      build:
        context: keycloak/
      environment:
        DB_VENDOR: postgres # Leave as-is if using PostgreSQL
        DB_ADDR: postgres # You can add an external SaaS DB address here
        DB_DATABASE: keycloak # Point to the production database here
        DB_USER: keycloak # Point to the production database here
        DB_SCHEMA: public # Usually left as-is
        DB_PASSWORD: password # Point to the production database here
        KEYCLOAK_USER: admin # You can usually leave this as-is
        KEYCLOAK_PASSWORD: admin # Change after 1st login in production!!
        KCBASE: /opt/jboss/keycloak/ # Leave as-is
        HS_REDIRECT_URI: http://localhost:8000/* # Don't bother
        HS_CLIENT_ALIAS: hs_playground
      ports:
        - 8080:8080
      depends_on:
        - postgres

  hs-auth-server:
      image: hypermine/hs-auth-server
      ports:
        - 3000:3000



