version: '3'

volumes:
  pgdata:
      driver: local  

services:
  postgres:
      image: postgres:12
      volumes:
        - pgdata:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password # don't expose this database outside!
      ports:
        - 5432:5432

  keycloak:
      build:
        context: keycloak/
      environment:
        DB_VENDOR: postgres # Leave as-is if using PostgreSQL
        DB_ADDR: postgres # Address of the PostgreSQL instance.
        DB_DATABASE: keycloak # PostgreSQL database name
        DB_USER: keycloak # PostgreSQL username
        DB_SCHEMA: public # PostgreSQL schema; Leave as-is.
        DB_PASSWORD: password # PostgreSQL password; don't expose this database outside!
        KEYCLOAK_USER: admin # You can usually leave this as-is
        KEYCLOAK_PASSWORD: admin # Change after 1st login in production!!to
        HS_REDIRECT_URI: http://localhost:8000/* # Change to whatever you need in prod!
        HS_CLIENT_ALIAS: hs_playground # Change to app's name!
        AUTH_FLOW_NAME: 'hs-auth-flow' # leave as-is or update to your own name
        HYPERSIGN_EXECUTION_NAME: 'Hypersign QR Code' # leave as-is or update to your own name
        HS_AUTH_SERVER_ENDPOINT: http://hs-auth-server:3000 # point to production hs-auth-server
      ports:
        - 8080:8080
      depends_on:
        - postgres
        - hs-auth-server

  hs-auth-server:
      image: hypermine/hs-auth-server
      ports:
        - 3000:3000



